services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_NAME: suri
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: sekret
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      RAILS_LOG_TO_STDOUT: 'true'
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
